# Next.js / Dev 用
FROM node:20-alpine AS base

WORKDIR /app

# 依存解決
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json apps/web/
COPY packages/ui/package.json packages/ui/
RUN npm install -g pnpm \
    && pnpm install --frozen-lockfile

COPY . .

WORKDIR /app/apps/web

# Next.js Dev Server
CMD ["pnpm", "run", "dev"]

EXPOSE 3000
