version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monolog_app_dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    working_dir: /app/apps/api
    volumes:
      - ./:/app:cached
      # SQLiteファイルをホスト上に永続化
      # - ./packages/db/dev.db:/app/packages/db/dev.db
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - API_PORT=${API_PORT}
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    working_dir: /app/apps/web
    volumes:
      - ./:/app:cached
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api

volumes:
  db-data: