import { Providers } from "./providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBarWrapper from './components/common/NavBarWrapper';
import { cookies } from 'next/headers';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // サーバーサイドでセッションからユーザーを取得
  const cookieStore = await cookies();
  const session = cookieStore.get('monolog_auth_user');
  let user = null;
  if (session) {
    try {
      user = JSON.parse(decodeURIComponent(session.value));
    } catch {}
  }
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <NavBarWrapper user={user} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
