version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:       ${POSTGRES_DB:-monolog_app_dev}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../packages/db/docker:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: api-dev
    working_dir: /app/apps/api
    volumes:
      - ../apps/api:/app/apps/api:cached
      - api_node_modules:/app/apps/api/node_modules
    env_file:
      - ../.env
    environment:
      NODE_ENV:       development
      DATABASE_URL:   ${DATABASE_URL}
      API_URL:        ${API_URL}
    ports:
      - "3001:3001"
    depends_on:
      - migrator

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: web-dev
    working_dir: /app/apps/web
    volumes:
      - ../:/app:cached
    env_file:
      - ../.env
    environment:
      NODE_ENV:            development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      API_URL:        ${API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - migrator

  migrator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: migrator
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  db-data:
  api_node_modules:
